using MarketPlace.Domain.Core.Application.Entities._Admin;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MarketPlace.Domain.Core.Application.Entities._Address;

namespace MarketPlace.Infra.Db.SqlServer.Ef.SeedData
{
    public class CitySeedData : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder.HasData(

                new City {Id = 1,Name = "کشکساری",ProvinceId = 1 },
                new City {Id = 2,Name = "سهند",ProvinceId = 1 },
                new City {Id = 3,Name = "سیس",ProvinceId = 1 },
                new City {Id = 4,Name = "دوزدوزان",ProvinceId = 1 },
                new City {Id = 5,Name = "تیمورلو",ProvinceId = 1 },
                new City {Id = 6,Name = "صوفیان",ProvinceId = 1 },
                new City {Id = 7,Name = "سردرود",ProvinceId = 1 },
                new City {Id = 8,Name = "هادیشهر",ProvinceId = 1 },
                new City {Id = 9,Name = "هشترود",ProvinceId = 1 },
                new City {Id = 10,Name = "زرنق",ProvinceId = 1 },
                new City {Id = 11,Name = "ترکمانچای",ProvinceId = 1 },
                new City {Id = 12,Name = "ورزقان",ProvinceId = 1 },
                new City {Id = 13,Name = "تسوج",ProvinceId = 1 },
                new City {Id = 14,Name = "زنوز",ProvinceId = 1 },
                new City {Id = 15,Name = "ایلخچی",ProvinceId = 1 },
                new City {Id = 16,Name = "شرفانه",ProvinceId = 1 },
                new City {Id = 17,Name = "مهربان",ProvinceId = 1 },
                new City {Id = 18,Name = "مبارک شهر",ProvinceId = 1 },
                new City {Id = 19,Name = "تیکمه داش",ProvinceId = 1 },
                new City {Id = 20,Name = "باسمنج",ProvinceId = 1 },
                new City {Id = 21,Name = "سیه رود",ProvinceId = 1 },
                new City {Id = 22,Name = "میانه",ProvinceId = 1 },
                new City {Id = 23,Name = "خمارلو",ProvinceId = 1 },
                new City {Id = 24,Name = "خواجه",ProvinceId = 1 },
                new City {Id = 25,Name = "بناب مرند",ProvinceId = 1 },
                new City {Id = 26,Name = "قره آغاج",ProvinceId = 1 },
                new City {Id = 27,Name = "وایقان",ProvinceId = 1 },
                new City {Id = 28,Name = "مراغه",ProvinceId = 1 },
                new City {Id = 29,Name = "ممقان",ProvinceId = 1 },
                new City {Id = 30,Name = "خامنه",ProvinceId = 1 },
                new City {Id = 31,Name = "خسروشاه",ProvinceId = 1 },
                new City {Id = 32,Name = "لیلان",ProvinceId = 1 },
                new City {Id = 33,Name = "نظرکهریزی",ProvinceId = 1 },
                new City {Id = 34,Name = "اهر",ProvinceId = 1 },
                new City {Id = 35,Name = "بخشایش",ProvinceId = 1 },
                new City {Id = 36,Name = "آقکند",ProvinceId = 1 },
                new City {Id = 37,Name = "جوان قلعه",ProvinceId = 1 },
                new City {Id = 38,Name = "کلیبر",ProvinceId = 1 },
                new City {Id = 39,Name = "مرند",ProvinceId = 1 },
                new City {Id = 40,Name = "اسکو",ProvinceId = 1 },
                new City {Id = 41,Name = "شندآباد",ProvinceId = 1 },
                new City {Id = 42,Name = "شربیان",ProvinceId = 1 },
                new City {Id = 43,Name = "گوگان",ProvinceId = 1 },
                new City {Id = 44,Name = "بستان آباد",ProvinceId = 1 },
                new City {Id = 45,Name = "تبریز",ProvinceId = 1 },
                new City {Id = 46,Name = "جلفا",ProvinceId = 1 },
                new City {Id = 47,Name = "اچاچی",ProvinceId = 1 },
                new City {Id = 48,Name = "هریس",ProvinceId = 1 },
                new City {Id = 49,Name = "یامچی",ProvinceId = 1 },
                new City {Id = 50,Name = "خاروانا",ProvinceId = 1 },
                new City {Id = 51,Name = "کوزه کنان",ProvinceId = 1 },
                new City {Id = 52,Name = "خداجو",ProvinceId = 1 },
                new City {Id = 53,Name = "آذرشهر",ProvinceId = 1 },
                new City {Id = 54,Name = "شبستر",ProvinceId = 1 },
                new City {Id = 55,Name = "سراب",ProvinceId = 1 },
                new City {Id = 56,Name = "ملکان",ProvinceId = 1 },
                new City {Id = 57,Name = "بناب",ProvinceId = 1 },
                new City {Id = 58,Name = "هوراند",ProvinceId = 1 },
                new City {Id = 59,Name = "کلوانق",ProvinceId = 1 },
                new City {Id = 60,Name = "ترک",ProvinceId = 1 },
                new City {Id = 61,Name = "عجب شیر",ProvinceId = 1 },
                new City {Id = 62,Name = "آبش احمد",ProvinceId = 1 },
                new City {Id = 63,Name = "تازه شهر",ProvinceId = 2 },
                new City {Id = 64,Name = "نالوس",ProvinceId = 2 },
                new City {Id = 65,Name = "ایواوغلی",ProvinceId = 2 },
                new City {Id = 66,Name = "شاهین دژ",ProvinceId = 2 },
                new City {Id = 67,Name = "گرد کشانه",ProvinceId = 2 },
                new City {Id = 68,Name = "باروق",ProvinceId = 2 },
                new City {Id = 69,Name = "سیلوانه",ProvinceId = 2 },
                new City {Id = 70,Name = "بازرگان",ProvinceId = 2 },
                new City {Id = 71,Name = "نازک علیا",ProvinceId = 2 },
                new City {Id = 72,Name = "ربط",ProvinceId = 2 },
                new City {Id = 73,Name = "تکاب",ProvinceId = 2 },
                new City {Id = 74,Name = "دیزج دیز",ProvinceId = 2 },
                new City {Id = 75,Name = "سیمینه",ProvinceId = 2 },
                new City {Id = 76,Name = "نوشین",ProvinceId = 2 },
                new City {Id = 77,Name = "میاندوآب",ProvinceId = 2 },
                new City {Id = 78,Name = "مرگنلر",ProvinceId = 2 },
                new City {Id = 79,Name = "سلماس",ProvinceId = 2 },
                new City {Id = 80,Name = "آواجیق",ProvinceId = 2 },
                new City {Id = 81,Name = "قطور",ProvinceId = 2 },
                new City {Id = 82,Name = "محمود آباد",ProvinceId = 2 },
                new City {Id = 83,Name = "خوی",ProvinceId = 2 },
                new City {Id = 84,Name = "نقده",ProvinceId = 2 },
                new City {Id = 85,Name = "سرو",ProvinceId = 2 },
                new City {Id = 86,Name = "خلیفان",ProvinceId = 2 },
                new City {Id = 87,Name = "پلدشت",ProvinceId = 2 },
                new City {Id = 88,Name = "میر آباد",ProvinceId = 2 },
                new City {Id = 89,Name = "اشنویه",ProvinceId = 2 },
                new City {Id = 90,Name = "زرآباد",ProvinceId = 2 },
                new City {Id = 91,Name = "بوکان",ProvinceId = 2 },
                new City {Id = 92,Name = "پیرانشهر",ProvinceId = 2 },
                new City {Id = 93,Name = "چهاربرج",ProvinceId = 2 },
                new City {Id = 94,Name = "قوشچی",ProvinceId = 2 },
                new City {Id = 95,Name = "شوط",ProvinceId = 2 },
                new City {Id = 96,Name = "ماکو",ProvinceId = 2 },
                new City {Id = 97,Name = "سیه چشمه",ProvinceId = 2 },
                new City {Id = 98,Name = "سردشت",ProvinceId = 2 },
                new City {Id = 99,Name = "کشاورز",ProvinceId = 2 },
                new City {Id = 100,Name = "فیروق",ProvinceId = 2 },
                new City {Id = 101,Name = "محمدیار",ProvinceId = 2 },
                new City {Id = 102,Name = "ارومیه",ProvinceId = 2 },
                new City {Id = 103,Name = "مهاباد",ProvinceId = 2 },
                new City {Id = 104,Name = "قره ضیاءالدین",ProvinceId = 2 },
                new City {Id = 105,Name = "پارس آباد",ProvinceId = 3 },
                new City {Id = 106,Name = "فخر آباد",ProvinceId = 3 },
                new City {Id = 107,Name = "کلور",ProvinceId = 3 },
                new City {Id = 108,Name = "نیر",ProvinceId = 3 },
                new City {Id = 109,Name = "اردبیل",ProvinceId = 3 },
                new City {Id = 110,Name = "اسلام آباد",ProvinceId = 3 },
                new City {Id = 111,Name = "تازه کندانگوت",ProvinceId = 3 },
                new City {Id = 112,Name = "مشکین شهر",ProvinceId = 3 },
                new City {Id = 113,Name = "جعفر اباد",ProvinceId = 3 },
                new City {Id = 114,Name = "مرادلو",ProvinceId = 3 },
                new City {Id = 115,Name = "خلخال",ProvinceId = 3 },
                new City {Id = 116,Name = "نمین",ProvinceId = 3 },
                new City {Id = 117,Name = "اصلاندوز",ProvinceId = 3 },
                new City {Id = 118,Name = "کوراییم",ProvinceId = 3 },
                new City {Id = 119,Name = "هیر",ProvinceId = 3 },
                new City {Id = 120,Name = "گیوی",ProvinceId = 3 },
                new City {Id = 121,Name = "گرمی",ProvinceId = 3 },
                new City {Id = 122,Name = "لاهرود",ProvinceId = 3 },
                new City {Id = 123,Name = "هشتجین",ProvinceId = 3 },
                new City {Id = 124,Name = "عنبران",ProvinceId = 3 },
                new City {Id = 125,Name = "تازهکند",ProvinceId = 3 },
                new City {Id = 126,Name = "قصابه",ProvinceId = 3 },
                new City {Id = 127,Name = "رضی",ProvinceId = 3 },
                new City {Id = 128,Name = "سرعین",ProvinceId = 3 },
                new City {Id = 129,Name = "بیله سوار",ProvinceId = 3 },
                new City {Id = 130,Name = "آبی بیگلو",ProvinceId = 3 },
                new City {Id = 131,Name = "گزبر خوار",ProvinceId = 4 },
                new City {Id = 132,Name = "زیار",ProvinceId = 4 },
                new City {Id = 133,Name = "زرین شهر",ProvinceId = 4 },
                new City {Id = 134,Name = "گلشن",ProvinceId = 4 },
                new City {Id = 135,Name = "پیربکران",ProvinceId = 4 },
                new City {Id = 136,Name = "خالدآباد",ProvinceId = 4 },
                new City {Id = 137,Name = "سجزی",ProvinceId = 4 },
                new City {Id = 138,Name = "گوگد",ProvinceId = 4 },
                new City {Id = 139,Name = "تیران",ProvinceId = 4 },
                new City {Id = 140,Name = "ونک",ProvinceId = 4 },
                new City {Id = 141,Name = "دهق",ProvinceId = 4 },
                new City {Id = 142,Name = "زواره",ProvinceId = 4 },
                new City {Id = 143,Name = "کاشان",ProvinceId = 4 },
                new City {Id = 144,Name = "ابوزیدآباد",ProvinceId = 4 },
                new City {Id = 145,Name = "اصغرآباد",ProvinceId = 4 },
                new City {Id = 146,Name = "بافران",ProvinceId = 4 },
                new City {Id = 147,Name = "شهرضا",ProvinceId = 4 },
                new City {Id = 148,Name = "خور",ProvinceId = 4 },
                new City {Id = 149,Name = "مجلسی",ProvinceId = 4 },
                new City {Id = 150,Name = "هرند",ProvinceId = 4 },
                new City {Id = 151,Name = "فولادشهر",ProvinceId = 4 },
                new City {Id = 152,Name = "کمشچه",ProvinceId = 4 },
                new City {Id = 153,Name = "کلیشادوسودرجان",ProvinceId = 4 },
                new City {Id = 154,Name = "لای بید",ProvinceId = 4 },
                new City {Id = 155,Name = "قهجاورستان",ProvinceId = 4 },
                new City {Id = 156,Name = "چرمهین",ProvinceId = 4 },
                new City {Id = 157,Name = "رزوه",ProvinceId = 4 },
                new City {Id = 158,Name = "فریدونشهر",ProvinceId = 4 },
                new City {Id = 159,Name = "طرقق رود",ProvinceId = 4 },
                new City {Id = 160,Name = "نصرآباد",ProvinceId = 4 },
                new City {Id = 161,Name = "برزک",ProvinceId = 4 },
                new City {Id = 162,Name = "سفید شهر",ProvinceId = 4 },
                new City {Id = 163,Name = "سمیرم",ProvinceId = 4 },
                new City {Id = 164,Name = "گلدشت",ProvinceId = 4 },
                new City {Id = 165,Name = "اردستان",ProvinceId = 4 },
                new City {Id = 166,Name = "جوشقان قالی",ProvinceId = 4 },
                new City {Id = 167,Name = "بویین و میاندشت",ProvinceId = 4 },
                new City {Id = 168,Name = "کرکوند",ProvinceId = 4 },
                new City {Id = 169,Name = "درچه",ProvinceId = 4 },
                new City {Id = 170,Name = "انارک",ProvinceId = 4 },
                new City {Id = 171,Name = "دولت اباد",ProvinceId = 4 },
                new City {Id = 172,Name = "ایمانشهر",ProvinceId = 4 },
                new City {Id = 173,Name = "گرگاب",ProvinceId = 4 },
                new City {Id = 174,Name = "حسن آباد",ProvinceId = 4 },
                new City {Id = 175,Name = "ده لنجان",ProvinceId = 4 },
                new City {Id = 176,Name = "حبیب آباد",ProvinceId = 4 },
                new City {Id = 177,Name = "بهاران شهر",ProvinceId = 4 },
                new City {Id = 178,Name = "میمه",ProvinceId = 4 },
                new City {Id = 179,Name = "تو دشت",ProvinceId = 4 },
                new City {Id = 180,Name = "گلشهر",ProvinceId = 4 },
                new City {Id = 181,Name = "رضوانشهر",ProvinceId = 4 },
                new City {Id = 182,Name = "داران",ProvinceId = 4 },
                new City {Id = 183,Name = "علویجه",ProvinceId = 4 },
                new City {Id = 184,Name = "نیک آباد",ProvinceId = 4 },
                new City {Id = 185,Name = "مشکات",ProvinceId = 4 },
                new City {Id = 186,Name = "آران و بیدگل",ProvinceId = 4 },
                new City {Id = 187,Name = "خوانسار",ProvinceId = 4 },
                new City {Id = 188,Name = "نجف آباد",ProvinceId = 4 },
                new City {Id = 189,Name = "منظریه",ProvinceId = 4 },
                new City {Id = 190,Name = "فرخی",ProvinceId = 4 },
                new City {Id = 191,Name = "دیزیچه",ProvinceId = 4 },
                new City {Id = 192,Name = "اژیه",ProvinceId = 4 },
                new City {Id = 193,Name = "زاینده رود",ProvinceId = 4 },
                new City {Id = 194,Name = "خورزوق",ProvinceId = 4 },
                new City {Id = 195,Name = "قهدریجان",ProvinceId = 4 },
                new City {Id = 196,Name = "شاهین شهر",ProvinceId = 4 },
                new City {Id = 197,Name = "بهارستان",ProvinceId = 4 },
                new City {Id = 198,Name = "چمگردان",ProvinceId = 4 },
                new City {Id = 199,Name = "دهاقان",ProvinceId = 4 },
                new City {Id = 200,Name = "برف انبار",ProvinceId = 4 },
                new City {Id = 201,Name = "بادرود",ProvinceId = 4 },
                new City {Id = 202,Name = "کوهپایه",ProvinceId = 4 },
                new City {Id = 203,Name = "گلپایگان",ProvinceId = 4 },
                new City {Id = 204,Name = "عسگران",ProvinceId = 4 },
                new City {Id = 205,Name = "حنا",ProvinceId = 4 },
                new City {Id = 206,Name = "کهریزک",ProvinceId = 4 },
                new City {Id = 207,Name = "مهاباد",ProvinceId = 4 },
                new City {Id = 208,Name = "کامو چوگان",ProvinceId = 4 },
                new City {Id = 209,Name = "افوس",ProvinceId = 4 },
                new City {Id = 210,Name = "زیبا شهر",ProvinceId = 4 },
                new City {Id = 211,Name = "کوشک",ProvinceId = 4 },
                new City {Id = 212,Name = "نایین",ProvinceId = 4 },
                new City {Id = 213,Name = "سین",ProvinceId = 4 },
                new City {Id = 214,Name = "زازران",ProvinceId = 4 },
                new City {Id = 215,Name = "مبارکه",ProvinceId = 4 },
                new City {Id = 216,Name = "ورزنه",ProvinceId = 4 },
                new City {Id = 217,Name = "ورنامخواست",ProvinceId = 4 },
                new City {Id = 218,Name = "شاپور آباد",ProvinceId = 4 },
                new City {Id = 219,Name = "فلاورجان",ProvinceId = 4 },
                new City {Id = 220,Name = "وزوان",ProvinceId = 4 },
                new City {Id = 221,Name = "اصفهان",ProvinceId = 4 },
                new City {Id = 222,Name = "باغ بهادران",ProvinceId = 4 },
                new City {Id = 223,Name = "چادگان",ProvinceId = 4 },
                new City {Id = 224,Name = "دامنه",ProvinceId = 4 },
                new City {Id = 225,Name = "نطنز",ProvinceId = 4 },
                new City {Id = 226,Name = "محمد آباد",ProvinceId = 4 },
                new City {Id = 227,Name = "نیاسر",ProvinceId = 4 },
                new City {Id = 228,Name = "نوش آباد",ProvinceId = 4 },
                new City {Id = 229,Name = "کمه",ProvinceId = 4 },
                new City {Id = 230,Name = "جوزدان",ProvinceId = 4 },
                new City {Id = 231,Name = "قمصر",ProvinceId = 4 },
                new City {Id = 232,Name = "جندق",ProvinceId = 4 },
                new City {Id = 233,Name = "طالخونچه",ProvinceId = 4 },
                new City {Id = 234,Name = "خمینی شهر",ProvinceId = 4 },
                new City {Id = 235,Name = "باغشاد",ProvinceId = 4 },
                new City {Id = 236,Name = "دستگرد",ProvinceId = 4 },
                new City {Id = 237,Name = "ابریشم",ProvinceId = 4 },
                new City {Id = 238,Name = "چهارباغ",ProvinceId = 5 },
                new City {Id = 239,Name = "آسارا",ProvinceId = 5 },
                new City {Id = 240,Name = "کرج",ProvinceId = 5 },
                new City {Id = 241,Name = "طالقان",ProvinceId = 5 },
                new City {Id = 242,Name = "شهرجدیدهشتگرد",ProvinceId = 5 },
                new City {Id = 243,Name = "محمدشهر",ProvinceId = 5 },
                new City {Id = 244,Name = "مشکین دشت",ProvinceId = 5 },
                new City {Id = 245,Name = "نظرآباد",ProvinceId = 5 },
                new City {Id = 246,Name = "هشتگرد",ProvinceId = 5 },
                new City {Id = 247,Name = "ماهدشت",ProvinceId = 5 },
                new City {Id = 248,Name = "اشتهارد",ProvinceId = 5 },
                new City {Id = 249,Name = "کوهسار",ProvinceId = 5 },
                new City {Id = 250,Name = "گرمدره",ProvinceId = 5 },
                new City {Id = 251,Name = "تنکمان",ProvinceId = 5 },
                new City {Id = 252,Name = "گلسار",ProvinceId = 5 },
                new City {Id = 253,Name = "کمالشهر",ProvinceId = 5 },
                new City {Id = 254,Name = "فردیس",ProvinceId = 5 },
                new City {Id = 255,Name = "آبدانان",ProvinceId = 6 },
                new City {Id = 256,Name = "شباب",ProvinceId = 6 },
                new City {Id = 257,Name = "موسیان",ProvinceId = 6 },
                new City {Id = 258,Name = "بدره",ProvinceId = 6 },
                new City {Id = 259,Name = "ایلام",ProvinceId = 6 },
                new City {Id = 260,Name = "ایوان",ProvinceId = 6 },
                new City {Id = 261,Name = "مهران",ProvinceId = 6 },
                new City {Id = 262,Name = "آسمان آباد",ProvinceId = 6 },
                new City {Id = 263,Name = "پهله",ProvinceId = 6 },
                new City {Id = 264,Name = "مهر",ProvinceId = 6 },
                new City {Id = 265,Name = "سراب باغ",ProvinceId = 6 },
                new City {Id = 266,Name = "بلاوه",ProvinceId = 6 },
                new City {Id = 267,Name = "میمه",ProvinceId = 6 },
                new City {Id = 268,Name = "دره شهر",ProvinceId = 6 },
                new City {Id = 269,Name = "ارکواز",ProvinceId = 6 },
                new City {Id = 270,Name = "مورموری",ProvinceId = 6 },
                new City {Id = 271,Name = "توحید",ProvinceId = 6 },
                new City {Id = 272,Name = "دهلران",ProvinceId = 6 },
                new City {Id = 273,Name = "لومار",ProvinceId = 6 },
                new City {Id = 274,Name = "چوار",ProvinceId = 6 },
                new City {Id = 275,Name = "زرنه",ProvinceId = 6 },
                new City {Id = 276,Name = "صالح آباد",ProvinceId = 6 },
                new City {Id = 277,Name = "سرابله",ProvinceId = 6 },
                new City {Id = 278,Name = "ماژین",ProvinceId = 6 },
                new City {Id = 279,Name = "دلگشا",ProvinceId = 6 },
                new City {Id = 280,Name = "ریز",ProvinceId = 7 },
                new City {Id = 281,Name = "برازجان",ProvinceId = 7 },
                new City {Id = 282,Name = "بندریگ",ProvinceId = 7 },
                new City {Id = 283,Name = "اهرم",ProvinceId = 7 },
                new City {Id = 284,Name = "دوراهک",ProvinceId = 7 },
                new City {Id = 285,Name = "خورموج",ProvinceId = 7 },
                new City {Id = 286,Name = "نخل تقی",ProvinceId = 7 },
                new City {Id = 287,Name = "کلمه",ProvinceId = 7 },
                new City {Id = 288,Name = "بندر دیلم",ProvinceId = 7 },
                new City {Id = 289,Name = "وحدتیه",ProvinceId = 7 },
                new City {Id = 290,Name = "بنک",ProvinceId = 7 },
                new City {Id = 291,Name = "چغادک",ProvinceId = 7 },
                new City {Id = 292,Name = "بندر دیر",ProvinceId = 7 },
                new City {Id = 293,Name = "کاکی",ProvinceId = 7 },
                new City {Id = 294,Name = "جم",ProvinceId = 7 },
                new City {Id = 295,Name = "دالکی",ProvinceId = 7 },
                new City {Id = 296,Name = "بندرگناوه",ProvinceId = 7 },
                new City {Id = 297,Name = "آبدان",ProvinceId = 7 },
                new City {Id = 298,Name = "خارک",ProvinceId = 7 },
                new City {Id = 299,Name = "شنبه",ProvinceId = 7 },
                new City {Id = 300,Name = "بوشکان",ProvinceId = 7 },
                new City {Id = 301,Name = "انارستان",ProvinceId = 7 },
                new City {Id = 302,Name = "شبانکاره",ProvinceId = 7 },
                new City {Id = 303,Name = "سیراف",ProvinceId = 7 },
                new City {Id = 304,Name = "دلوار",ProvinceId = 7 },
                new City {Id = 305,Name = "بردستان",ProvinceId = 7 },
                new City {Id = 306,Name = "بادوله",ProvinceId = 7 },
                new City {Id = 307,Name = "عسلویه",ProvinceId = 7 },
                new City {Id = 308,Name = "تنگ ارم",ProvinceId = 7 },
                new City {Id = 309,Name = "امام حسن",ProvinceId = 7 },
                new City {Id = 310,Name = "سعد آباد",ProvinceId = 7 },
                new City {Id = 311,Name = "بندرکنگان",ProvinceId = 7 },
                new City {Id = 312,Name = "بوشهر",ProvinceId = 7 },
                new City {Id = 313,Name = "بردخون",ProvinceId = 7 },
                new City {Id = 314,Name = "آب پخش",ProvinceId = 7 },
                new City {Id = 315,Name = "شاهدشهر",ProvinceId = 8 },
                new City {Id = 316,Name = "پیشوا",ProvinceId = 8 },
                new City {Id = 317,Name = "جواد آباد",ProvinceId = 8 },
                new City {Id = 318,Name = "ارجمند",ProvinceId = 8 },
                new City {Id = 319,Name = "ری",ProvinceId = 8 },
                new City {Id = 320,Name = "نصیرشهر",ProvinceId = 8 },
                new City {Id = 321,Name = "رودهن",ProvinceId = 8 },
                new City {Id = 322,Name = "اندیشه",ProvinceId = 8 },
                new City {Id = 323,Name = "نسیم شهر",ProvinceId = 8 },
                new City {Id = 324,Name = "صباشهر",ProvinceId = 8 },
                new City {Id = 325,Name = "ملارد",ProvinceId = 8 },
                new City {Id = 326,Name = "شمشک",ProvinceId = 8 },
                new City {Id = 327,Name = "پاکدشت",ProvinceId = 8 },
                new City {Id = 328,Name = "باقر شهر",ProvinceId = 8 },
                new City {Id = 329,Name = "احمد آباد مستوفی",ProvinceId = 8 },
                new City {Id = 330,Name = "کیلان",ProvinceId = 8 },
                new City {Id = 331,Name = "قرچک",ProvinceId = 8 },
                new City {Id = 332,Name = "فردوسیه",ProvinceId = 8 },
                new City {Id = 333,Name = "گلستان",ProvinceId = 8 },
                new City {Id = 334,Name = "ورامین",ProvinceId = 8 },
                new City {Id = 335,Name = "فیروزکوه",ProvinceId = 8 },
                new City {Id = 336,Name = "فشم",ProvinceId = 8 },
                new City {Id = 337,Name = "پرند",ProvinceId = 8 },
                new City {Id = 338,Name = "آبعلی",ProvinceId = 8 },
                new City {Id = 339,Name = "چهاردانگه",ProvinceId = 8 },
                new City {Id = 340,Name = "تهران",ProvinceId = 8 },
                new City {Id = 341,Name = "بومهن",ProvinceId = 8 },
                new City {Id = 342,Name = "وحیدیه",ProvinceId = 8 },
                new City {Id = 343,Name = "صفادشت",ProvinceId = 8 },
                new City {Id = 344,Name = "لواسان",ProvinceId = 8 },
                new City {Id = 345,Name = "فرون اباد",ProvinceId = 8 },
                new City {Id = 346,Name = "کهریزک",ProvinceId = 8 },
                new City {Id = 347,Name = "رباطکریم",ProvinceId = 8 },
                new City {Id = 348,Name = "آبسرد",ProvinceId = 8 },
                new City {Id = 349,Name = "باغستان",ProvinceId = 8 },
                new City {Id = 350,Name = "صالحیه",ProvinceId = 8 },
                new City {Id = 351,Name = "شهریار",ProvinceId = 8 },
                new City {Id = 352,Name = "قدس",ProvinceId = 8 },
                new City {Id = 353,Name = "تجریش",ProvinceId = 8 },
                new City {Id = 354,Name = "شریف آباد",ProvinceId = 8 },
                new City {Id = 355,Name = "حسن آباد",ProvinceId = 8 },
                new City {Id = 356,Name = "اسلامشهر",ProvinceId = 8 },
                new City {Id = 357,Name = "دماوند",ProvinceId = 8 },
                new City {Id = 358,Name = "پردیس",ProvinceId = 8 },
                new City {Id = 359,Name = "وردنجان",ProvinceId = 9 },
                new City {Id = 360,Name = "گوجان",ProvinceId = 9 },
                new City {Id = 361,Name = "گهرو",ProvinceId = 9 },
                new City {Id = 362,Name = "سورشجان",ProvinceId = 9 },
                new City {Id = 363,Name = "سرخون",ProvinceId = 9 },
                new City {Id = 364,Name = "شهرکرد",ProvinceId = 9 },
                new City {Id = 365,Name = "منج",ProvinceId = 9 },
                new City {Id = 366,Name = "بروجن",ProvinceId = 9 },
                new City {Id = 367,Name = "پردنجان",ProvinceId = 9 },
                new City {Id = 368,Name = "سامان",ProvinceId = 9 },
                new City {Id = 369,Name = "فرخشهر",ProvinceId = 9 },
                new City {Id = 370,Name = "صمصامی",ProvinceId = 9 },
                new City {Id = 371,Name = "طاقانک",ProvinceId = 9 },
                new City {Id = 372,Name = "کاج",ProvinceId = 9 },
                new City {Id = 373,Name = "نقنه",ProvinceId = 9 },
                new City {Id = 374,Name = "لردگان",ProvinceId = 9 },
                new City {Id = 375,Name = "باباحیدر",ProvinceId = 9 },
                new City {Id = 376,Name = "دستنا",ProvinceId = 9 },
                new City {Id = 377,Name = "سودجان",ProvinceId = 9 },
                new City {Id = 378,Name = "بازفت",ProvinceId = 9 },
                new City {Id = 379,Name = "هفشجان",ProvinceId = 9 },
                new City {Id = 380,Name = "سردشت",ProvinceId = 9 },
                new City {Id = 381,Name = "فرادبنه",ProvinceId = 9 },
                new City {Id = 382,Name = "چلیچه",ProvinceId = 9 },
                new City {Id = 383,Name = "بن",ProvinceId = 9 },
                new City {Id = 384,Name = "فارسان",ProvinceId = 9 },
                new City {Id = 385,Name = "شلمزار",ProvinceId = 9 },
                new City {Id = 386,Name = "نافچ",ProvinceId = 9 },
                new City {Id = 387,Name = "دشتک",ProvinceId = 9 },
                new City {Id = 388,Name = "بلداجی",ProvinceId = 9 },
                new City {Id = 389,Name = "آلونی",ProvinceId = 9 },
                new City {Id = 390,Name = "گندمان",ProvinceId = 9 },
                new City {Id = 391,Name = "جونقان",ProvinceId = 9 },
                new City {Id = 392,Name = "ناغان",ProvinceId = 9 },
                new City {Id = 393,Name = "هارونی",ProvinceId = 9 },
                new City {Id = 394,Name = "چلگرد",ProvinceId = 9 },
                new City {Id = 395,Name = "کیان",ProvinceId = 9 },
                new City {Id = 396,Name = "اردل",ProvinceId = 9 },
                new City {Id = 397,Name = "سفید دشت",ProvinceId = 9 },
                new City {Id = 398,Name = "مال خلیفه",ProvinceId = 9 },
                new City {Id = 399,Name = "اسلامیه",ProvinceId = 10 },
                new City {Id = 400,Name = "شوسف",ProvinceId = 10 },
                new City {Id = 401,Name = "قاین",ProvinceId = 10 },
                new City {Id = 402,Name = "عشقآباد",ProvinceId = 10 },
                new City {Id = 403,Name = "طبس مسینا",ProvinceId = 10 },
                new City {Id = 404,Name = "ارسک",ProvinceId = 10 },
                new City {Id = 405,Name = "ایسک",ProvinceId = 10 },
                new City {Id = 406,Name = "نیمبلوک",ProvinceId = 10 },
                new City {Id = 407,Name = "دهوک",ProvinceId = 10 },
                new City {Id = 408,Name = "سربیشه",ProvinceId = 10 },
                new City {Id = 409,Name = "محمد شهر",ProvinceId = 10 },
                new City {Id = 410,Name = "بیرجند",ProvinceId = 10 },
                new City {Id = 411,Name = "فردوس",ProvinceId = 10 },
                new City {Id = 412,Name = "نهبندان",ProvinceId = 10 },
                new City {Id = 413,Name = "اسفدن",ProvinceId = 10 },
                new City {Id = 414,Name = "گریزک",ProvinceId = 10 },
                new City {Id = 415,Name = "حاجی آباد",ProvinceId = 10 },
                new City {Id = 416,Name = "سه قلعه",ProvinceId = 10 },
                new City {Id = 417,Name = "آرین شهر",ProvinceId = 10 },
                new City {Id = 418,Name = "مود",ProvinceId = 10 },
                new City {Id = 419,Name = "خوسف",ProvinceId = 10 },
                new City {Id = 420,Name = "قهستان",ProvinceId = 10 },
                new City {Id = 421,Name = "بشرویه",ProvinceId = 10 },
                new City {Id = 422,Name = "سرایان",ProvinceId = 10 },
                new City {Id = 423,Name = "خضری دشت بیاض",ProvinceId = 10 },
                new City {Id = 424,Name = "طبس",ProvinceId = 10 },
                new City {Id = 425,Name = "اسدیه",ProvinceId = 10 },
                new City {Id = 426,Name = "زهان",ProvinceId = 10 },
                new City {Id = 427,Name = "بار",ProvinceId = 11 },
                new City {Id = 428,Name = "نیل شهر",ProvinceId = 11 },
                new City {Id = 429,Name = "جنگل",ProvinceId = 11 },
                new City {Id = 430,Name = "درود",ProvinceId = 11 },
                new City {Id = 431,Name = "رباط سنگ",ProvinceId = 11 },
                new City {Id = 432,Name = "سلطان آباد",ProvinceId = 11 },
                new City {Id = 433,Name = "فریمان",ProvinceId = 11 },
                new City {Id = 434,Name = "گناباد",ProvinceId = 11 },
                new City {Id = 435,Name = "کاریز",ProvinceId = 11 },
                new City {Id = 436,Name = "همت آباد",ProvinceId = 11 },
                new City {Id = 437,Name = "سلامی",ProvinceId = 11 },
                new City {Id = 438,Name = "باجگیران",ProvinceId = 11 },
                new City {Id = 439,Name = "بجستان",ProvinceId = 11 },
                new City {Id = 440,Name = "چناران",ProvinceId = 11 },
                new City {Id = 441,Name = "درگز",ProvinceId = 11 },
                new City {Id = 442,Name = "کلات",ProvinceId = 11 },
                new City {Id = 443,Name = "چکنه",ProvinceId = 11 },
                new City {Id = 444,Name = "نصرآباد",ProvinceId = 11 },
                new City {Id = 445,Name = "بردسکن",ProvinceId = 11 },
                new City {Id = 446,Name = "مشهد",ProvinceId = 11 },
                new City {Id = 447,Name = "کدکن",ProvinceId = 11 },
                new City {Id = 448,Name = "نقاب",ProvinceId = 11 },
                new City {Id = 449,Name = "قلندر آباد",ProvinceId = 11 },
                new City {Id = 450,Name = "کاشمر",ProvinceId = 11 },
                new City {Id = 451,Name = "شاندیز",ProvinceId = 11 },
                new City {Id = 452,Name = "نشتیفان",ProvinceId = 11 },
                new City {Id = 453,Name = "ششتمد",ProvinceId = 11 },
                new City {Id = 454,Name = "شادمهر",ProvinceId = 11 },
                new City {Id = 455,Name = "عشق آباد",ProvinceId = 11 },
                new City {Id = 456,Name = "چاپشلو",ProvinceId = 11 },
                new City {Id = 457,Name = "رشتخوار",ProvinceId = 11 },
                new City {Id = 458,Name = "قدمگاه",ProvinceId = 11 },
                new City {Id = 459,Name = "صالح آباد",ProvinceId = 11 },
                new City {Id = 460,Name = "داورزن",ProvinceId = 11 },
                new City {Id = 461,Name = "فرهادگرد",ProvinceId = 11 },
                new City {Id = 462,Name = "کاخک",ProvinceId = 11 },
                new City {Id = 463,Name = "مشهدریزه",ProvinceId = 11 },
                new City {Id = 464,Name = "جغتای",ProvinceId = 11 },
                new City {Id = 465,Name = "مزدآوند",ProvinceId = 11 },
                new City {Id = 466,Name = "قوچان",ProvinceId = 11 },
                new City {Id = 467,Name = "یونسی",ProvinceId = 11 },
                new City {Id = 468,Name = "سنگان",ProvinceId = 11 },
                new City {Id = 469,Name = "نوخندان",ProvinceId = 11 },
                new City {Id = 470,Name = "کندر",ProvinceId = 11 },
                new City {Id = 471,Name = "نیشابور",ProvinceId = 11 },
                new City {Id = 472,Name = "احمد آباد صولت",ProvinceId = 11 },
                new City {Id = 473,Name = "شهر آباد",ProvinceId = 11 },
                new City {Id = 474,Name = "رضویه",ProvinceId = 11 },
                new City {Id = 475,Name = "تربت حیدریه",ProvinceId = 11 },
                new City {Id = 476,Name = "باخرز",ProvinceId = 11 },
                new City {Id = 477,Name = "سفیدسنگ",ProvinceId = 11 },
                new City {Id = 478,Name = "بیدخت",ProvinceId = 11 },
                new City {Id = 479,Name = "تایباد",ProvinceId = 11 },
                new City {Id = 480,Name = "فیروزه",ProvinceId = 11 },
                new City {Id = 481,Name = "قاسم آباد",ProvinceId = 11 },
                new City {Id = 482,Name = "سبزوار",ProvinceId = 11 },
                new City {Id = 483,Name = "فیض آباد",ProvinceId = 11 },
                new City {Id = 484,Name = "گلمکان",ProvinceId = 11 },
                new City {Id = 485,Name = "لطف آباد",ProvinceId = 11 },
                new City {Id = 486,Name = "شهروز",ProvinceId = 11 },
                new City {Id = 487,Name = "خرو",ProvinceId = 11 },
                new City {Id = 488,Name = "تربت جام",ProvinceId = 11 },
                new City {Id = 489,Name = "انابد",ProvinceId = 11 },
                new City {Id = 490,Name = "ملک آباد",ProvinceId = 11 },
                new City {Id = 491,Name = "بایک",ProvinceId = 11 },
                new City {Id = 492,Name = "دولت آباد",ProvinceId = 11 },
                new City {Id = 493,Name = "سرخس",ProvinceId = 11 },
                new City {Id = 494,Name = "ریوش",ProvinceId = 11 },
                new City {Id = 495,Name = "طرقبه",ProvinceId = 11 },
                new City {Id = 496,Name = "خواف",ProvinceId = 11 },
                new City {Id = 497,Name = "روداب",ProvinceId = 11 },
                new City {Id = 498,Name = "خلیل آباد",ProvinceId = 11 },
                new City {Id = 499,Name = "چناران شهر",ProvinceId = 11 },
                new City {Id = 500,Name = "راز",ProvinceId = 12 },
                new City {Id = 501,Name = "پیش قلعه",ProvinceId = 12 },
                new City {Id = 502,Name = "قوشخانه",ProvinceId = 12 },
                new City {Id = 503,Name = "شوقان",ProvinceId = 12 },
                new City {Id = 504,Name = "اسفراین",ProvinceId = 12 },
                new City {Id = 505,Name = "گرمه",ProvinceId = 12 },
                new City {Id = 506,Name = "قاضی",ProvinceId = 12 },
                new City {Id = 507,Name = "شیروان",ProvinceId = 12 },
                new City {Id = 508,Name = "حسار گرمخان",ProvinceId = 12 },
                new City {Id = 509,Name = "آشخانه",ProvinceId = 12 },
                new City {Id = 510,Name = "تیتکانلو",ProvinceId = 12 },
                new City {Id = 511,Name = "جاجرم",ProvinceId = 12 },
                new City {Id = 512,Name = "بجنورد",ProvinceId = 12 },
                new City {Id = 513,Name = "درق",ProvinceId = 12 },
                new City {Id = 514,Name = "آوا",ProvinceId = 12 },
                new City {Id = 515,Name = "زیارت",ProvinceId = 12 },
                new City {Id = 516,Name = "سنخواست",ProvinceId = 12 },
                new City {Id = 517,Name = "صفی آباد",ProvinceId = 12 },
                new City {Id = 518,Name = "ایور",ProvinceId = 12 },
                new City {Id = 519,Name = "فاروج",ProvinceId = 12 },
                new City {Id = 520,Name = "لوجلی",ProvinceId = 12 },
                new City {Id = 521,Name = "هفتگل",ProvinceId = 13 },
                new City {Id = 522,Name = "بیدروبه",ProvinceId = 13 },
                new City {Id = 523,Name = "شاوور",ProvinceId = 13 },
                new City {Id = 524,Name = "حمزه",ProvinceId = 13 },
                new City {Id = 525,Name = "گتوند",ProvinceId = 13 },
                new City {Id = 526,Name = "شرافت",ProvinceId = 13 },
                new City {Id = 527,Name = "منصوریه",ProvinceId = 13 },
                new City {Id = 528,Name = "زهره",ProvinceId = 13 },
                new City {Id = 529,Name = "رامهرمز",ProvinceId = 13 },
                new City {Id = 530,Name = "بندرامام خمینی",ProvinceId = 13 },
                new City {Id = 531,Name = "کوت عبدالله",ProvinceId = 13 },
                new City {Id = 532,Name = "میداود",ProvinceId = 13 },
                new City {Id = 533,Name = "چغامیش",ProvinceId = 13 },
                new City {Id = 534,Name = "ملاثانی",ProvinceId = 13 },
                new City {Id = 535,Name = "چم گلک",ProvinceId = 13 },
                new City {Id = 536,Name = "حر",ProvinceId = 13 },
                new City {Id = 537,Name = "شمس آباد",ProvinceId = 13 },
                new City {Id = 538,Name = "آبژدان",ProvinceId = 13 },
                new City {Id = 539,Name = "چویبده",ProvinceId = 13 },
                new City {Id = 540,Name = "مسجد سلیمان",ProvinceId = 13 },
                new City {Id = 541,Name = "مقاومت",ProvinceId = 13 },
                new City {Id = 542,Name = "ترکالکی",ProvinceId = 13 },
                new City {Id = 543,Name = "دارخوین",ProvinceId = 13 },
                new City {Id = 544,Name = "سردشت",ProvinceId = 13 },
                new City {Id = 545,Name = "لالی",ProvinceId = 13 },
                new City {Id = 546,Name = "کوت سیدنعیم",ProvinceId = 13 },
                new City {Id = 547,Name = "حمیدیه",ProvinceId = 13 },
                new City {Id = 548,Name = "دهدز",ProvinceId = 13 },
                new City {Id = 549,Name = "قلعه تل",ProvinceId = 13 },
                new City {Id = 550,Name = "میانرود",ProvinceId = 13 },
                new City {Id = 551,Name = "رفیع",ProvinceId = 13 },
                new City {Id = 552,Name = "اندیمشک",ProvinceId = 13 },
                new City {Id = 553,Name = "الوان",ProvinceId = 13 },
                new City {Id = 554,Name = "سالند",ProvinceId = 13 },
                new City {Id = 555,Name = "صالح شهر",ProvinceId = 13 },
                new City {Id = 556,Name = "اروندکنار",ProvinceId = 13 },
                new City {Id = 557,Name = "سرداران",ProvinceId = 13 },
                new City {Id = 558,Name = "تشان",ProvinceId = 13 },
                new City {Id = 559,Name = "رامشیر",ProvinceId = 13 },
                new City {Id = 560,Name = "شادگان",ProvinceId = 13 },
                new City {Id = 561,Name = "بندر ماهشهر",ProvinceId = 13 },
                new City {Id = 562,Name = "جایزان",ProvinceId = 13 },
                new City {Id = 563,Name = "بستان",ProvinceId = 13 },
                new City {Id = 564,Name = "ویس",ProvinceId = 13 },
                new City {Id = 565,Name = "اهواز",ProvinceId = 13 },
                new City {Id = 566,Name = "فتح المبین",ProvinceId = 13 },
                new City {Id = 567,Name = "شهر امام",ProvinceId = 13 },
                new City {Id = 568,Name = "قلعه خاجو",ProvinceId = 13 },
                new City {Id = 569,Name = "حسینیه",ProvinceId = 13 },
                new City {Id = 570,Name = "گلگیر",ProvinceId = 13 },
                new City {Id = 571,Name = "مینوشهر",ProvinceId = 13 },
                new City {Id = 572,Name = "سماله",ProvinceId = 13 },
                new City {Id = 573,Name = "شوشتر",ProvinceId = 13 },
                new City {Id = 574,Name = "بهبهان",ProvinceId = 13 },
                new City {Id = 575,Name = "هندیجان",ProvinceId = 13 },
                new City {Id = 576,Name = "ابوحمیظه",ProvinceId = 13 },
                new City {Id = 577,Name = "آغاجاری",ProvinceId = 13 },
                new City {Id = 578,Name = "ایذه",ProvinceId = 13 },
                new City {Id = 579,Name = "صیدون",ProvinceId = 13 },
                new City {Id = 580,Name = "سیاه منصور",ProvinceId = 13 },
                new City {Id = 581,Name = "هویزه",ProvinceId = 13 },
                new City {Id = 582,Name = "آزادی",ProvinceId = 13 },
                new City {Id = 583,Name = "شوش",ProvinceId = 13 },
                new City {Id = 584,Name = "دزفول",ProvinceId = 13 },
                new City {Id = 585,Name = "جنت مکان",ProvinceId = 13 },
                new City {Id = 586,Name = "آبادان",ProvinceId = 13 },
                new City {Id = 587,Name = "گوریه",ProvinceId = 13 },
                new City {Id = 588,Name = "خرمشهر",ProvinceId = 13 },
                new City {Id = 589,Name = "مشراگه",ProvinceId = 13 },
                new City {Id = 590,Name = "خنافره",ProvinceId = 13 },
                new City {Id = 591,Name = "چمران",ProvinceId = 13 },
                new City {Id = 592,Name = "امیدیه",ProvinceId = 13 },
                new City {Id = 593,Name = "سوسنگرد",ProvinceId = 13 },
                new City {Id = 594,Name = "شیبان",ProvinceId = 13 },
                new City {Id = 595,Name = "الهایی",ProvinceId = 13 },
                new City {Id = 596,Name = "باغ الملک",ProvinceId = 13 },
                new City {Id = 597,Name = "صفی آباد",ProvinceId = 13 },
                new City {Id = 598,Name = "سجاس",ProvinceId = 14 },
                new City {Id = 599,Name = "زرین رود",ProvinceId = 14 },
                new City {Id = 600,Name = "آب بر",ProvinceId = 14 },
                new City {Id = 601,Name = "ارمغانخانه",ProvinceId = 14 },
                new City {Id = 602,Name = "کرسف",ProvinceId = 14 },
                new City {Id = 603,Name = "هیدج",ProvinceId = 14 },
                new City {Id = 604,Name = "سلطانیه",ProvinceId = 14 },
                new City {Id = 605,Name = "خرمدره",ProvinceId = 14 },
                new City {Id = 606,Name = "نیک پی",ProvinceId = 14 },
                new City {Id = 607,Name = "قیدار",ProvinceId = 14 },
                new City {Id = 608,Name = "ابهر",ProvinceId = 14 },
                new City {Id = 609,Name = "دندی",ProvinceId = 14 },
                new City {Id = 610,Name = "حلب",ProvinceId = 14 },
                new City {Id = 611,Name = "نوربهار",ProvinceId = 14 },
                new City {Id = 612,Name = "گرماب",ProvinceId = 14 },
                new City {Id = 613,Name = "چورزق",ProvinceId = 14 },
                new City {Id = 614,Name = "زنجان",ProvinceId = 14 },
                new City {Id = 615,Name = "سهرود",ProvinceId = 14 },
                new City {Id = 616,Name = "صایین قلعه",ProvinceId = 14 },
                new City {Id = 617,Name = "ماه نشان",ProvinceId = 14 },
                new City {Id = 618,Name = "زرین آباد",ProvinceId = 14 },
                new City {Id = 619,Name = "ایوانکی",ProvinceId = 15 },
                new City {Id = 620,Name = "مجن",ProvinceId = 15 },
                new City {Id = 621,Name = "دامغان",ProvinceId = 15 },
                new City {Id = 622,Name = "سرخه",ProvinceId = 15 },
                new City {Id = 623,Name = "مهدیشهر",ProvinceId = 15 },
                new City {Id = 624,Name = "شاهرود",ProvinceId = 15 },
                new City {Id = 625,Name = "سمنان",ProvinceId = 15 },
                new City {Id = 626,Name = "کهن آباد",ProvinceId = 15 },
                new City {Id = 627,Name = "گرمسار",ProvinceId = 15 },
                new City {Id = 628,Name = "کلاته خیج",ProvinceId = 15 },
                new City {Id = 629,Name = "دیباج",ProvinceId = 15 },
                new City {Id = 630,Name = "درجزین",ProvinceId = 15 },
                new City {Id = 631,Name = "رودیان",ProvinceId = 15 },
                new City {Id = 632,Name = "بسطام",ProvinceId = 15 },
                new City {Id = 633,Name = "امیریه",ProvinceId = 15 },
                new City {Id = 634,Name = "میامی",ProvinceId = 15 },
                new City {Id = 635,Name = "شهمیزاد",ProvinceId = 15 },
                new City {Id = 636,Name = "بیارجمند",ProvinceId = 15 },
                new City {Id = 637,Name = "کلاته",ProvinceId = 15 },
                new City {Id = 638,Name = "آردان",ProvinceId = 15 },
                new City {Id = 639,Name = "محمدی",ProvinceId = 16 },
                new City {Id = 640,Name = "شهرک غلی اکبر",ProvinceId = 16 },
                new City {Id = 641,Name = "بنجار",ProvinceId = 16 },
                new City {Id = 642,Name = "گلمورتی",ProvinceId = 16 },
                new City {Id = 643,Name = "نگور",ProvinceId = 16 },
                new City {Id = 644,Name = "راسک",ProvinceId = 16 },
                new City {Id = 645,Name = "بنت",ProvinceId = 16 },
                new City {Id = 646,Name = "قصرقند",ProvinceId = 16 },
                new City {Id = 647,Name = "جالق",ProvinceId = 16 },
                new City {Id = 648,Name = "هیدوچ",ProvinceId = 16 },
                new City {Id = 649,Name = "نوک آباد",ProvinceId = 16 },
                new City {Id = 650,Name = "زهک",ProvinceId = 16 },
                new City {Id = 651,Name = "بمپور",ProvinceId = 16 },
                new City {Id = 652,Name = "پیشین",ProvinceId = 16 },
                new City {Id = 653,Name = "گشت",ProvinceId = 16 },
                new City {Id = 654,Name = "محمد آباد",ProvinceId = 16 },
                new City {Id = 655,Name = "زاهدان",ProvinceId = 16 },
                new City {Id = 656,Name = "",ProvinceId = 16 },
                new City {Id = 657,Name = "زابلی",ProvinceId = 16 },
                new City {Id = 658,Name = "چابهار",ProvinceId = 16 },
                new City {Id = 659,Name = "زراباد",ProvinceId = 16 },
                new City {Id = 660,Name = "بزمان",ProvinceId = 16 },
                new City {Id = 661,Name = "اسپکه",ProvinceId = 16 },
                new City {Id = 662,Name = "فنوچ",ProvinceId = 16 },
                new City {Id = 663,Name = "سراوان",ProvinceId = 16 },
                new City {Id = 664,Name = "ادیمی",ProvinceId = 16 },
                new City {Id = 665,Name = "زابل",ProvinceId = 16 },
                new City {Id = 666,Name = "دوشت محمد",ProvinceId = 16 },
                new City {Id = 667,Name = "ایرانشهر",ProvinceId = 16 },
                new City {Id = 668,Name = "سرباز",ProvinceId = 16 },
                new City {Id = 669,Name = "سیرکان",ProvinceId = 16 },
                new City {Id = 670,Name = "میرجاوه",ProvinceId = 16 },
                new City {Id = 671,Name = "نصرت آباد",ProvinceId = 16 },
                new City {Id = 672,Name = "سوران",ProvinceId = 16 },
                new City {Id = 673,Name = "خاش",ProvinceId = 16 },
                new City {Id = 674,Name = "کنارک",ProvinceId = 16 },
                new City {Id = 675,Name = "محمدان",ProvinceId = 16 },
                new City {Id = 676,Name = "نیک شهر",ProvinceId = 16 },
                new City {Id = 677,Name = "کازرون",ProvinceId = 17 },
                new City {Id = 678,Name = "کارزین(فتح اباد)",ProvinceId = 17 },
                new City {Id = 679,Name = "فدامی",ProvinceId = 17 },
                new City {Id = 680,Name = "خومه زار",ProvinceId = 17 },
                new City {Id = 681,Name = "سلطان شهر",ProvinceId = 17 },
                new City {Id = 682,Name = "فیروز آباد",ProvinceId = 17 },
                new City {Id = 683,Name = "دبیران",ProvinceId = 17 },
                new City {Id = 684,Name = "باب انار",ProvinceId = 17 },
                new City {Id = 685,Name = "رامجرد",ProvinceId = 17 },
                new City {Id = 686,Name = "سروستان",ProvinceId = 17 },
                new City {Id = 687,Name = "قره بلاغ",ProvinceId = 17 },
                new City {Id = 688,Name = "ارسنجان",ProvinceId = 17 },
                new City {Id = 689,Name = "دژکرد",ProvinceId = 17 },
                new City {Id = 690,Name = "بیرم",ProvinceId = 17 },
                new City {Id = 691,Name = "دهرم",ProvinceId = 17 },
                new City {Id = 692,Name = "شیراز",ProvinceId = 17 },
                new City {Id = 693,Name = "ایزدخواست",ProvinceId = 17 },
                new City {Id = 694,Name = "علامرودشت",ProvinceId = 17 },
                new City {Id = 695,Name = "اوز",ProvinceId = 17 },
                new City {Id = 696,Name = "وراوی",ProvinceId = 17 },
                new City {Id = 697,Name = "بیضا",ProvinceId = 17 },
                new City {Id = 698,Name = "نیریز",ProvinceId = 17 },
                new City {Id = 699,Name = "کنار تخته",ProvinceId = 17 },
                new City {Id = 700,Name = "امام شهر",ProvinceId = 17 },
                new City {Id = 701,Name = "جهرم",ProvinceId = 17 },
                new City {Id = 702,Name = "بابا منیر",ProvinceId = 17 },
                new City {Id = 703,Name = "گراش",ProvinceId = 17 },
                new City {Id = 704,Name = "فسا",ProvinceId = 17 },
                new City {Id = 705,Name = "شهر پیر",ProvinceId = 17 },
                new City {Id = 706,Name = "حسن آباد",ProvinceId = 17 },
                new City {Id = 707,Name = "کامفیروز",ProvinceId = 17 },
                new City {Id = 708,Name = "خنج",ProvinceId = 17 },
                new City {Id = 709,Name = "خانه زنیان",ProvinceId = 17 },
                new City {Id = 710,Name = "استهبان",ProvinceId = 17 },
                new City {Id = 711,Name = "بوانات",ProvinceId = 17 },
                new City {Id = 712,Name = "لطیفی",ProvinceId = 17 },
                new City {Id = 713,Name = "فراشبند",ProvinceId = 17 },
                new City {Id = 714,Name = "زرقان",ProvinceId = 17 },
                new City {Id = 715,Name = "صغاد",ProvinceId = 17 },
                new City {Id = 716,Name = "اشکنان",ProvinceId = 17 },
                new City {Id = 717,Name = "قایمیه",ProvinceId = 17 },
                new City {Id = 718,Name = "گله دار",ProvinceId = 17 },
                new City {Id = 719,Name = "دوبرجی",ProvinceId = 17 },
                new City {Id = 720,Name = "آباده طشک",ProvinceId = 17 },
                new City {Id = 721,Name = "خرامه",ProvinceId = 17 },
                new City {Id = 722,Name = "میمند",ProvinceId = 17 },
                new City {Id = 723,Name = "افزر",ProvinceId = 17 },
                new City {Id = 724,Name = "دوزه",ProvinceId = 17 },
                new City {Id = 725,Name = "سیدان",ProvinceId = 17 },
                new City {Id = 726,Name = "کوپن",ProvinceId = 17 },
                new City {Id = 727,Name = "زاهدشهر",ProvinceId = 17 },
                new City {Id = 728,Name = "قادر آباد",ProvinceId = 17 },
                new City {Id = 729,Name = "سده",ProvinceId = 17 },
                new City {Id = 730,Name = "بنارویه",ProvinceId = 17 },
                new City {Id = 731,Name = "سعادت شهر",ProvinceId = 17 },
                new City {Id = 732,Name = "شهر صدرا",ProvinceId = 17 },
                new City {Id = 733,Name = "سورمق",ProvinceId = 17 },
                new City {Id = 734,Name = "حسامی",ProvinceId = 17 },
                new City {Id = 735,Name = "جویم",ProvinceId = 17 },
                new City {Id = 736,Name = "خوزی",ProvinceId = 17 },
                new City {Id = 737,Name = "اردکان",ProvinceId = 17 },
                new City {Id = 738,Name = "قطرویه",ProvinceId = 17 },
                new City {Id = 739,Name = "نودان",ProvinceId = 17 },
                new City {Id = 740,Name = "مبارک آباد دیز",ProvinceId = 17 },
                new City {Id = 741,Name = "داراب",ProvinceId = 17 },
                new City {Id = 742,Name = "نور آباد",ProvinceId = 17 },
                new City {Id = 743,Name = "کوار",ProvinceId = 17 },
                new City {Id = 744,Name = "نوبندگان",ProvinceId = 17 },
                new City {Id = 745,Name = "حاجی آباد",ProvinceId = 17 },
                new City {Id = 746,Name = "خاوران",ProvinceId = 17 },
                new City {Id = 747,Name = "مرودشت",ProvinceId = 17 },
                new City {Id = 748,Name = "کوهنجان",ProvinceId = 17 },
                new City {Id = 749,Name = "ششده",ProvinceId = 17 },
                new City {Id = 750,Name = "مزایجان",ProvinceId = 17 },
                new City {Id = 751,Name = "ایج",ProvinceId = 17 },
                new City {Id = 752,Name = "خور",ProvinceId = 17 },
                new City {Id = 753,Name = "نوجین",ProvinceId = 17 },
                new City {Id = 754,Name = "لپویی",ProvinceId = 17 },
                new City {Id = 755,Name = "بهمن",ProvinceId = 17 },
                new City {Id = 756,Name = "اهل",ProvinceId = 17 },
                new City {Id = 757,Name = "خشت",ProvinceId = 17 },
                new City {Id = 758,Name = "مهر",ProvinceId = 17 },
                new City {Id = 759,Name = "جنت شهر",ProvinceId = 17 },
                new City {Id = 760,Name = "مشکان",ProvinceId = 17 },
                new City {Id = 761,Name = "بالاده",ProvinceId = 17 },
                new City {Id = 762,Name = "قیر",ProvinceId = 17 },
                new City {Id = 763,Name = "قطب آباد",ProvinceId = 17 },
                new City {Id = 764,Name = "خانیمن",ProvinceId = 17 },
                new City {Id = 765,Name = "مصیری",ProvinceId = 17 },
                new City {Id = 766,Name = "میانشهر",ProvinceId = 17 },
                new City {Id = 767,Name = "صفاشهر",ProvinceId = 17 },
                new City {Id = 768,Name = "اقلید",ProvinceId = 17 },
                new City {Id = 769,Name = "عمادده",ProvinceId = 17 },
                new City {Id = 770,Name = "مادر سلیمان",ProvinceId = 17 },
                new City {Id = 771,Name = "داریان",ProvinceId = 17 },
                new City {Id = 772,Name = "رونیز",ProvinceId = 17 },
                new City {Id = 773,Name = "کره ای",ProvinceId = 17 },
                new City {Id = 774,Name = "لار",ProvinceId = 17 },
                new City {Id = 775,Name = "اسیر",ProvinceId = 17 },
                new City {Id = 776,Name = "هماشهر",ProvinceId = 17 },
                new City {Id = 777,Name = "آباده",ProvinceId = 17 },
                new City {Id = 778,Name = "لامرد",ProvinceId = 17 },
                new City {Id = 779,Name = "سگز آباد",ProvinceId = 18 },
                new City {Id = 780,Name = "بیدستان",ProvinceId = 18 },
                new City {Id = 781,Name = "کوهین",ProvinceId = 18 },
                new City {Id = 782,Name = "رازمیان",ProvinceId = 18 },
                new City {Id = 783,Name = "خرمدشت",ProvinceId = 18 },
                new City {Id = 784,Name = "آبگرم",ProvinceId = 18 },
                new City {Id = 785,Name = "شال",ProvinceId = 18 },
                new City {Id = 786,Name = "شریفیه",ProvinceId = 18 },
                new City {Id = 787,Name = "اقبالیه",ProvinceId = 18 },
                new City {Id = 788,Name = "نرجه",ProvinceId = 18 },
                new City {Id = 789,Name = "ارداق",ProvinceId = 18 },
                new City {Id = 790,Name = "الوند",ProvinceId = 18 },
                new City {Id = 791,Name = "خاکعلی",ProvinceId = 18 },
                new City {Id = 792,Name = "سیردان",ProvinceId = 18 },
                new City {Id = 793,Name = "ضیاد آباد",ProvinceId = 18 },
                new City {Id = 794,Name = "بویین زهرا",ProvinceId = 18 },
                new City {Id = 795,Name = "محمدیه",ProvinceId = 18 },
                new City {Id = 796,Name = "محمود آباد نمونه",ProvinceId = 18 },
                new City {Id = 797,Name = "معلم کلایه",ProvinceId = 18 },
                new City {Id = 798,Name = "اسفرورین",ProvinceId = 18 },
                new City {Id = 799,Name = "آوج",ProvinceId = 18 },
                new City {Id = 800,Name = "دانسفهان",ProvinceId = 18 },
                new City {Id = 801,Name = "آبیک",ProvinceId = 18 },
                new City {Id = 802,Name = "قزوین",ProvinceId = 18 },
                new City {Id = 803,Name = "تاکستان",ProvinceId = 18 },
                new City {Id = 804,Name = "کهک",ProvinceId = 19 },
                new City {Id = 805,Name = "قم",ProvinceId = 19 },
                new City {Id = 806,Name = "سلفچگان",ProvinceId = 19 },
                new City {Id = 807,Name = "جعفریه",ProvinceId = 19 },
                new City {Id = 808,Name = "قنوات",ProvinceId = 19 },
                new City {Id = 809,Name = "دستجرد",ProvinceId = 19 },
                new City {Id = 810,Name = "توپ آغاج",ProvinceId = 20 },
                new City {Id = 811,Name = "سرو آباد",ProvinceId = 20 },
                new City {Id = 812,Name = "بویین سفلی",ProvinceId = 20 },
                new City {Id = 813,Name = "زرینه",ProvinceId = 20 },
                new City {Id = 814,Name = "دلبران",ProvinceId = 20 },
                new City {Id = 815,Name = "سنندج",ProvinceId = 20 },
                new City {Id = 816,Name = "یاسوکند",ProvinceId = 20 },
                new City {Id = 817,Name = "موچش",ProvinceId = 20 },
                new City {Id = 818,Name = "بانه",ProvinceId = 20 },
                new City {Id = 819,Name = "مریوان",ProvinceId = 20 },
                new City {Id = 820,Name = "سریش آباد",ProvinceId = 20 },
                new City {Id = 821,Name = "صاحب",ProvinceId = 20 },
                new City {Id = 822,Name = "دهگلان",ProvinceId = 20 },
                new City {Id = 823,Name = "بابارشانی",ProvinceId = 20 },
                new City {Id = 824,Name = "دیواندره",ProvinceId = 20 },
                new City {Id = 825,Name = "برده رشه",ProvinceId = 20 },
                new City {Id = 826,Name = "شویشه",ProvinceId = 20 },
                new City {Id = 827,Name = "بیجار",ProvinceId = 20 },
                new City {Id = 828,Name = "اورامان تخت",ProvinceId = 20 },
                new City {Id = 829,Name = "کانی سور",ProvinceId = 20 },
                new City {Id = 830,Name = "کانی دینار",ProvinceId = 20 },
                new City {Id = 831,Name = "دزج",ProvinceId = 20 },
                new City {Id = 832,Name = "سقز",ProvinceId = 20 },
                new City {Id = 833,Name = "بلبان آباد",ProvinceId = 20 },
                new City {Id = 834,Name = "پیرتاج",ProvinceId = 20 },
                new City {Id = 835,Name = "کامیاران",ProvinceId = 20 },
                new City {Id = 836,Name = "آرمرده",ProvinceId = 20 },
                new City {Id = 837,Name = "چناره",ProvinceId = 20 },
                new City {Id = 838,Name = "کهنوج",ProvinceId = 21 },
                new City {Id = 839,Name = "بلوک",ProvinceId = 21 },
                new City {Id = 840,Name = "پاریز",ProvinceId = 21 },
                new City {Id = 841,Name = "گنبکی",ProvinceId = 21 },
                new City {Id = 842,Name = "زنگی آباد",ProvinceId = 21 },
                new City {Id = 843,Name = "بم",ProvinceId = 21 },
                new City {Id = 844,Name = "خانوک",ProvinceId = 21 },
                new City {Id = 845,Name = "کیانشهر",ProvinceId = 21 },
                new City {Id = 846,Name = "جوپار",ProvinceId = 21 },
                new City {Id = 847,Name = "عنبرآباد",ProvinceId = 21 },
                new City {Id = 848,Name = "جوزم",ProvinceId = 21 },
                new City {Id = 849,Name = "نظام شهر",ProvinceId = 21 },
                new City {Id = 850,Name = "لاله زار",ProvinceId = 21 },
                new City {Id = 851,Name = "کشکوییه",ProvinceId = 21 },
                new City {Id = 852,Name = "زید آباد",ProvinceId = 21 },
                new City {Id = 853,Name = "هنزا",ProvinceId = 21 },
                new City {Id = 854,Name = "چترود",ProvinceId = 21 },
                new City {Id = 855,Name = "جبالبارز",ProvinceId = 21 },
                new City {Id = 856,Name = "سیرجان",ProvinceId = 21 },
                new City {Id = 857,Name = "رودبار",ProvinceId = 21 },
                new City {Id = 858,Name = "کرمان",ProvinceId = 21 },
                new City {Id = 859,Name = "بافت",ProvinceId = 21 },
                new City {Id = 860,Name = "صفاییه",ProvinceId = 21 },
                new City {Id = 861,Name = "منوجان",ProvinceId = 21 },
                new City {Id = 862,Name = "اندوهجرد",ProvinceId = 21 },
                new City {Id = 863,Name = "هجدک",ProvinceId = 21 },
                new City {Id = 864,Name = "خورسند",ProvinceId = 21 },
                new City {Id = 865,Name = "امین شهر",ProvinceId = 21 },
                new City {Id = 866,Name = "بردسیر",ProvinceId = 21 },
                new City {Id = 867,Name = "رفسنجان",ProvinceId = 21 },
                new City {Id = 868,Name = "هما شهر",ProvinceId = 21 },
                new City {Id = 869,Name = "محمد آباد",ProvinceId = 21 },
                new City {Id = 870,Name = "اختیار آباد",ProvinceId = 21 },
                new City {Id = 871,Name = "بروات",ProvinceId = 21 },
                new City {Id = 872,Name = "ریحان",ProvinceId = 21 },
                new City {Id = 873,Name = "کوهبنان",ProvinceId = 21 },
                new City {Id = 874,Name = "ماهان",ProvinceId = 21 },
                new City {Id = 875,Name = "دوساری",ProvinceId = 21 },
                new City {Id = 876,Name = "دهج",ProvinceId = 21 },
                new City {Id = 877,Name = "فاریاب",ProvinceId = 21 },
                new City {Id = 878,Name = "گلزار",ProvinceId = 21 },
                new City {Id = 879,Name = "بهرمان",ProvinceId = 21 },
                new City {Id = 880,Name = "بلورد",ProvinceId = 21 },
                new City {Id = 881,Name = "فهرج",ProvinceId = 21 },
                new City {Id = 882,Name = "کاظم آباد",ProvinceId = 21 },
                new City {Id = 883,Name = "جیرفت",ProvinceId = 21 },
                new City {Id = 884,Name = "نجف شهر",ProvinceId = 21 },
                new City {Id = 885,Name = "قلعه گنج",ProvinceId = 21 },
                new City {Id = 886,Name = "باغین",ProvinceId = 21 },
                new City {Id = 887,Name = "بزنجان",ProvinceId = 21 },
                new City {Id = 888,Name = "زرند",ProvinceId = 21 },
                new City {Id = 889,Name = "نودژ",ProvinceId = 21 },
                new City {Id = 890,Name = "گلباف",ProvinceId = 21 },
                new City {Id = 891,Name = "راور",ProvinceId = 21 },
                new City {Id = 892,Name = "خاتون آباد",ProvinceId = 21 },
                new City {Id = 893,Name = "نرماشیر",ProvinceId = 21 },
                new City {Id = 894,Name = "دشتکار",ProvinceId = 21 },
                new City {Id = 895,Name = "مس سرچشمه",ProvinceId = 21 },
                new City {Id = 896,Name = "خواجو شهر",ProvinceId = 21 },
                new City {Id = 897,Name = "رابر",ProvinceId = 21 },
                new City {Id = 898,Name = "راین",ProvinceId = 21 },
                new City {Id = 899,Name = "درب بهشت",ProvinceId = 21 },
                new City {Id = 900,Name = "یزدان شهر",ProvinceId = 21 },
                new City {Id = 901,Name = "زهکلوت",ProvinceId = 21 },
                new City {Id = 902,Name = "محی آباد",ProvinceId = 21 },
                new City {Id = 903,Name = "مردهک",ProvinceId = 21 },
                new City {Id = 904,Name = "شهداد",ProvinceId = 21 },
                new City {Id = 905,Name = "ارزوییه",ProvinceId = 21 },
                new City {Id = 906,Name = "نگار",ProvinceId = 21 },
                new City {Id = 907,Name = "شهر بابک",ProvinceId = 21 },
                new City {Id = 908,Name = "انار",ProvinceId = 21 },
                new City {Id = 909,Name = "سنقر",ProvinceId = 22 },
                new City {Id = 910,Name = "شاهو",ProvinceId = 22 },
                new City {Id = 911,Name = "بانوره",ProvinceId = 22 },
                new City {Id = 912,Name = "تازه آباد",ProvinceId = 22 },
                new City {Id = 913,Name = "هلشی",ProvinceId = 22 },
                new City {Id = 914,Name = "جوانرود",ProvinceId = 22 },
                new City {Id = 915,Name = "قصرشیرین",ProvinceId = 22 },
                new City {Id = 916,Name = "نوسود",ProvinceId = 22 },
                new City {Id = 917,Name = "کرند",ProvinceId = 22 },
                new City {Id = 918,Name = "کوزران",ProvinceId = 22 },
                new City {Id = 919,Name = "بیستون",ProvinceId = 22 },
                new City {Id = 920,Name = "حمیل",ProvinceId = 22 },
                new City {Id = 921,Name = "گیلانغرب",ProvinceId = 22 },
                new City {Id = 922,Name = "سطر",ProvinceId = 22 },
                new City {Id = 923,Name = "روانسر",ProvinceId = 22 },
                new City {Id = 924,Name = "پاوه",ProvinceId = 22 },
                new City {Id = 925,Name = "ازگله",ProvinceId = 22 },
                new City {Id = 926,Name = "کرمانشاه",ProvinceId = 22 },
                new City {Id = 927,Name = "میان راهان",ProvinceId = 22 },
                new City {Id = 928,Name = "کنگاور",ProvinceId = 22 },
                new City {Id = 929,Name = "سرپل ذهاب",ProvinceId = 22 },
                new City {Id = 930,Name = "ریجاب",ProvinceId = 22 },
                new City {Id = 931,Name = "باینگان",ProvinceId = 22 },
                new City {Id = 932,Name = "هرسین",ProvinceId = 22 },
                new City {Id = 933,Name = "اسلام آباد غرب",ProvinceId = 22 },
                new City {Id = 934,Name = "سرمست",ProvinceId = 22 },
                new City {Id = 935,Name = "سومار",ProvinceId = 22 },
                new City {Id = 936,Name = "نودشه",ProvinceId = 22 },
                new City {Id = 937,Name = "گهواره",ProvinceId = 22 },
                new City {Id = 938,Name = "رباط",ProvinceId = 22 },
                new City {Id = 939,Name = "صحنه",ProvinceId = 22 },
                new City {Id = 940,Name = "گودین",ProvinceId = 22 },
                new City {Id = 941,Name = "گراب سفلی",ProvinceId = 23 },
                new City {Id = 942,Name = "لنده",ProvinceId = 23 },
                new City {Id = 943,Name = "سی سخت",ProvinceId = 23 },
                new City {Id = 944,Name = "دهدشت",ProvinceId = 23 },
                new City {Id = 945,Name = "یاسوج",ProvinceId = 23 },
                new City {Id = 946,Name = "سرفاریاب",ProvinceId = 23 },
                new City {Id = 947,Name = "دوگنبدان",ProvinceId = 23 },
                new City {Id = 948,Name = "چیتاب",ProvinceId = 23 },
                new City {Id = 949,Name = "لیکک",ProvinceId = 23 },
                new City {Id = 950,Name = "دیشموک",ProvinceId = 23 },
                new City {Id = 951,Name = "مادوان",ProvinceId = 23 },
                new City {Id = 952,Name = "باشت",ProvinceId = 23 },
                new City {Id = 953,Name = "پاتاوه",ProvinceId = 23 },
                new City {Id = 954,Name = "قلعه رییسی",ProvinceId = 23 },
                new City {Id = 955,Name = "مارگون",ProvinceId = 23 },
                new City {Id = 956,Name = "چرام",ProvinceId = 23 },
                new City {Id = 957,Name = "سوق",ProvinceId = 23 },
                new City {Id = 958,Name = "سیمین شهر",ProvinceId = 24 },
                new City {Id = 959,Name = "مزرعه",ProvinceId = 24 },
                new City {Id = 960,Name = "رامیان",ProvinceId = 24 },
                new City {Id = 961,Name = "فراغی",ProvinceId = 24 },
                new City {Id = 962,Name = "گنبد کاووس",ProvinceId = 24 },
                new City {Id = 963,Name = "کردکوی",ProvinceId = 24 },
                new City {Id = 964,Name = "مراوه",ProvinceId = 24 },
                new City {Id = 965,Name = "بندر ترکمن",ProvinceId = 24 },
                new City {Id = 966,Name = "نگین شهر",ProvinceId = 24 },
                new City {Id = 967,Name = "آق قلا",ProvinceId = 24 },
                new City {Id = 968,Name = "سرخنکلاته",ProvinceId = 24 },
                new City {Id = 969,Name = "گلیکش",ProvinceId = 24 },
                new City {Id = 970,Name = "سنگدوین",ProvinceId = 24 },
                new City {Id = 971,Name = "دلند",ProvinceId = 24 },
                new City {Id = 972,Name = "بندر گز",ProvinceId = 24 },
                new City {Id = 973,Name = "نوده خاندوز",ProvinceId = 24 },
                new City {Id = 974,Name = "مینودشت",ProvinceId = 24 },
                new City {Id = 975,Name = "گرگان",ProvinceId = 24 },
                new City {Id = 976,Name = "گمیش تپه",ProvinceId = 24 },
                new City {Id = 977,Name = "علی آباد",ProvinceId = 24 },
                new City {Id = 978,Name = "خان ببین",ProvinceId = 24 },
                new City {Id = 979,Name = "کلاله",ProvinceId = 24 },
                new City {Id = 980,Name = "اینچه برون",ProvinceId = 24 },
                new City {Id = 981,Name = "فاضل آباد",ProvinceId = 24 },
                new City {Id = 982,Name = "تاتار علیا",ProvinceId = 24 },
                new City {Id = 983,Name = "نو کنده",ProvinceId = 24 },
                new City {Id = 984,Name = "آزادشهر",ProvinceId = 24 },
                new City {Id = 985,Name = "انبار آلوم",ProvinceId = 24 },
                new City {Id = 986,Name = "جلین",ProvinceId = 24 },
                new City {Id = 987,Name = "منجیل",ProvinceId = 25 },
                new City {Id = 988,Name = "شلمان",ProvinceId = 25 },
                new City {Id = 989,Name = "خشکبیجار",ProvinceId = 25 },
                new City {Id = 990,Name = "ماکلوان",ProvinceId = 25 },
                new City {Id = 991,Name = "سنگر",ProvinceId = 25 },
                new City {Id = 992,Name = "مرجقل",ProvinceId = 25 },
                new City {Id = 993,Name = "لیسار",ProvinceId = 25 },
                new City {Id = 994,Name = "رضوانشهر",ProvinceId = 25 },
                new City {Id = 995,Name = "رحیم آباد",ProvinceId = 25 },
                new City {Id = 996,Name = "لوندویل",ProvinceId = 25 },
                new City {Id = 997,Name = "احمد سرگوراب",ProvinceId = 25 },
                new City {Id = 998,Name = "لوشان",ProvinceId = 25 },
                new City {Id = 999,Name = "اطاقور",ProvinceId = 25 },
                new City {Id = 1001,Name = "لشت نشاء",ProvinceId = 25 },
                new City {Id = 1002,Name = "فومن",ProvinceId = 25 },
                new City {Id = 1003,Name = "چوبر",ProvinceId = 25 },
                new City {Id = 1004,Name = "بازار جمعه",ProvinceId = 25 },
                new City {Id = 1005,Name = "کلاچای",ProvinceId = 25 },
                new City {Id = 1006,Name = "بندر انزلی",ProvinceId = 25 },
                new City {Id = 1007,Name = "املش",ProvinceId = 25 },
                new City {Id = 1008,Name = "رستم آباد",ProvinceId = 25 },
                new City {Id = 1009,Name = "لاهیجان",ProvinceId = 25 },
                new City {Id = 1010,Name = "توتکابن",ProvinceId = 25 },
                new City {Id = 1011,Name = "لنگرود",ProvinceId = 25 },
                new City {Id = 1012,Name = "کوچصفهان",ProvinceId = 25 },
                new City {Id = 1013,Name = "صومعه سرا",ProvinceId = 25 },
                new City {Id = 1014,Name = "اسالم",ProvinceId = 25 },
                new City {Id = 1015,Name = "دیلمان",ProvinceId = 25 },
                new City {Id = 1016,Name = "رودسر",ProvinceId = 25 },
                new City {Id = 1017,Name = "کیاشهر",ProvinceId = 25 },
                new City {Id = 1018,Name = "شفت",ProvinceId = 25 },
                new City {Id = 1019,Name = "رودبار",ProvinceId = 25 },
                new City {Id = 1020,Name = "کومله",ProvinceId = 25 },
                new City {Id = 1021,Name = "رشت",ProvinceId = 25 },
                new City {Id = 1022,Name = "ماسوله",ProvinceId = 25 },
                new City {Id = 1023,Name = "خمام",ProvinceId = 25 },
                new City {Id = 1024,Name = "ماسال",ProvinceId = 25 },
                new City {Id = 1025,Name = "واجارگاه",ProvinceId = 25 },
                new City {Id = 1026,Name = "هشتپر (تالش)",ProvinceId = 25 },
                new City {Id = 1027,Name = "پره سر",ProvinceId = 25 },
                new City {Id = 1028,Name = "بره سر",ProvinceId = 25 },
                new City {Id = 1029,Name = "آستارا",ProvinceId = 25 },
                new City {Id = 1030,Name = "رودبنه",ProvinceId = 25 },
                new City {Id = 1031,Name = "جیرنده",ProvinceId = 25 },
                new City {Id = 1032,Name = "چاف و چمخاله",ProvinceId = 25 },
                new City {Id = 1033,Name = "لولمان",ProvinceId = 25 },
                new City {Id = 1034,Name = "گوراب زرمیخ",ProvinceId = 25 },
                new City {Id = 1035,Name = "حویق",ProvinceId = 25 },
                new City {Id = 1036,Name = "سیاهکل",ProvinceId = 25 },
                new City {Id = 1037,Name = "چابکسر",ProvinceId = 25 },
                new City {Id = 1038,Name = "آستانه اشرفیه",ProvinceId = 25 },
                new City {Id = 1039,Name = "رانکوه",ProvinceId = 25 },
                new City {Id = 1040,Name = "چلانچولان",ProvinceId = 26 },
                new City {Id = 1041,Name = "بیران شهر",ProvinceId = 26 },
                new City {Id = 1042,Name = "ویسیان",ProvinceId = 26 }
                );
        }
    }
    public class ProvinceSeedData : IEntityTypeConfiguration<Province>
    {
        public void Configure(EntityTypeBuilder<Province> builder)
        {
            builder.HasData(
                new Province { Id = 1,Name = "آذربایجان شرقی"},
                new Province { Id = 2,Name = "آذربایجان غربی"},
                new Province { Id = 3,Name = "اردبیل"},
                new Province { Id = 4,Name = "اصفهان"},
                new Province { Id = 5,Name = "البرز"},
                new Province { Id = 6,Name = "ایلام"},
                new Province { Id = 7,Name = "بوشهر"},
                new Province { Id = 8,Name = "تهران"},
                new Province { Id = 9,Name = "چهارمحال بختیاری"},
                new Province { Id = 10,Name = "خراسان جنوبی"},
                new Province { Id = 11,Name = "خراسان رضوی"},
                new Province { Id = 12,Name = "خراسان شمالی"},
                new Province { Id = 13,Name = "خوزستان"},
                new Province { Id = 14,Name = "زنجان"},
                new Province { Id = 15,Name = "سمنان"},
                new Province { Id = 16,Name = "سیستان و بلوچستان"},
                new Province { Id = 17,Name = "فارس"},
                new Province { Id = 18,Name = "قزوین"},
                new Province { Id = 19,Name = "قم"},
                new Province { Id = 20,Name = "کردستان"},
                new Province { Id = 21,Name = "کرمان"},
                new Province { Id = 22,Name = "کرمانشاه"},
                new Province { Id = 23,Name = "کهکیلویه و بویراحمد"},
                new Province { Id = 24,Name = "گلستان"},
                new Province { Id = 25,Name = "گیلان"},
                new Province { Id = 26,Name = "لرستان"},
                new Province { Id = 27,Name = "مازندران"},
                new Province { Id = 28,Name = "مرکزی"},
                new Province { Id = 29,Name = "هرمزگان"},
                new Province { Id = 30,Name = "همدان"},
                new Province { Id = 31,Name = "یزد"}
                );
        }
    }
    public class MainAddressSeedData : IEntityTypeConfiguration<MainAddress>
    {
        public void Configure(EntityTypeBuilder<MainAddress> builder)
        {
            builder.HasData(
                new MainAddress { Id = 1,CityId=1, PostalCode= 1626627277,CreatedAt = DateTime.Now,Address = "خیابان رحمت جنب کوچه 2"},
                new MainAddress { Id = 2,CityId=1, PostalCode= 1234567890,CreatedAt = DateTime.Now,Address = "خیابان ملاصدرا جنب کوچه 2"},
                new MainAddress { Id = 3,CityId=1, PostalCode= 1634567611,CreatedAt = DateTime.Now,Address = "خیابان شهناز جنب کوچه 2"},
                new MainAddress { Id = 4,CityId=1, PostalCode= 1634567611,CreatedAt = DateTime.Now,Address = "خیابان شهناز جنب کوچه 2"},
                new MainAddress { Id = 5,CityId=2, PostalCode= 1713435657,CreatedAt = DateTime.Now,Address = "خیابان داریوش جنب کوچه 2"}
                );
        }
    }
}
